services:
  modelapi:
    build: .
    container_name: twinran-aiaas
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: >
        CMD-SHELL python -c "import http.client,os,sys;
        p=int(os.getenv('PORT','8000'));
        c=http.client.HTTPConnection('127.0.0.1',p,timeout=2);
        c.request('GET','/health');
        sys.exit(0 if c.getresponse().status==200 else 1)"
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app/app
        - action: sync
          path: ./ml-models
          target: /app/ml-models
